name: Build ZMK firmware
on:
  workflow_dispatch: # manual
  pull_request:
  push:
    paths:
      - ".github/workflows/build.yaml"
      - "build.yaml"
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/*.conf"
      - "config/west.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release-github:
    name: Github Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all commits and tags
      
      - name: Create tag
        id: tag
        run: echo "TAG=v1.0.${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Retrieve Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: build/
  
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.tag }}
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}